
spring:
  application:
    name: grpc-service-multi-instance

server:
  port: 0

armeria:
  ports:
  - port: ${GRPC_SERVER_PORT:55555}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
