
spring:
  application:
    name: rest-service
  main:
    web-application-type: none
    
armeria:
  ports:
    - port: 8081
      protocols:
        - HTTP
  internal-services:
    include: docs, health, metrics, actuator
    port: 8091

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

